from train.train_category_classification import train_category_classifier
from train.train_tps import train_tps
from train.train_emasc import train_emasc
from train.train_inversion_adapter import train_inversion_adapter
from train.train_vto import train_vto
